package nutrisoft;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_menu = new javax.swing.JPanel();
        btn_imc = new javax.swing.JButton();
        btn_gastoCalorico = new javax.swing.JButton();
        btn_recomendacao = new javax.swing.JButton();
        label_edwardlacerda = new javax.swing.JLabel();
        label_nutrisoft = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_menu.setPreferredSize(new java.awt.Dimension(400, 410));

        btn_imc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_imc.setText("IMC");
        btn_imc.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btn_imc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imcActionPerformed(evt);
            }
        });

        btn_gastoCalorico.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_gastoCalorico.setText("Gasto Calórico");
        btn_gastoCalorico.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btn_gastoCalorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gastoCaloricoActionPerformed(evt);
            }
        });

        btn_recomendacao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_recomendacao.setText("Recomendações");
        btn_recomendacao.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btn_recomendacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recomendacaoActionPerformed(evt);
            }
        });

        label_edwardlacerda.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        label_edwardlacerda.setText("Designed by Edward Lacerda");

        label_nutrisoft.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label_nutrisoft.setText("NutriSoft");

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_edwardlacerda))
                    .addGroup(panel_menuLayout.createSequentialGroup()
                        .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_menuLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(label_nutrisoft))
                            .addGroup(panel_menuLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_gastoCalorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_recomendacao, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(btn_imc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label_nutrisoft)
                .addGap(46, 46, 46)
                .addComponent(btn_imc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_gastoCalorico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_recomendacao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(label_edwardlacerda)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gastoCaloricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gastoCaloricoActionPerformed
        GastoCalorico telaGastoCalorico = new GastoCalorico();
        telaGastoCalorico.setVisible(true);
        telaGastoCalorico.setTitle("Nutrisoft - Gasto Calórico");
        telaGastoCalorico.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_gastoCaloricoActionPerformed

    private void btn_imcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imcActionPerformed
        Imc telaImc = new Imc();
        telaImc.setVisible(true);
        telaImc.setTitle("Nutrisoft - IMC");
        telaImc.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_imcActionPerformed

    private void btn_recomendacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recomendacaoActionPerformed
        Recomendacao telaRecomendacao = new Recomendacao();
        telaRecomendacao.setVisible(true);
        telaRecomendacao.setTitle("Nutrisoft - Recomendação");
        telaRecomendacao.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_recomendacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gastoCalorico;
    private javax.swing.JButton btn_imc;
    private javax.swing.JButton btn_recomendacao;
    private javax.swing.JLabel label_edwardlacerda;
    private javax.swing.JLabel label_nutrisoft;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}
