package nutrisoft;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author eddie
 */
public class Imc extends javax.swing.JFrame {

    /**
     * Creates new form Imc
     */
    public Imc() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_imc = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();
        panel_calculo = new javax.swing.JPanel();
        label_altura = new javax.swing.JLabel();
        label_peso = new javax.swing.JLabel();
        txt_peso = new javax.swing.JTextField();
        txt_altura = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        panel_resultado = new javax.swing.JPanel();
        label_resultado = new javax.swing.JLabel();
        label_interpretacao = new javax.swing.JLabel();
        label_edwardlacerda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_imc.setPreferredSize(new java.awt.Dimension(410, 416));

        label_titulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label_titulo.setText("Cálculo de IMC");

        panel_calculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label_altura.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label_altura.setText("Altura (M):");

        label_peso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label_peso.setText("Peso (K):");

        btn_calcular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_calculoLayout = new javax.swing.GroupLayout(panel_calculo);
        panel_calculo.setLayout(panel_calculoLayout);
        panel_calculoLayout.setHorizontalGroup(
            panel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_calculoLayout.createSequentialGroup()
                .addGroup(panel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_calculoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_calculoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_altura)
                            .addComponent(label_peso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(panel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_peso, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txt_altura))))
                .addGap(16, 16, 16))
        );
        panel_calculoLayout.setVerticalGroup(
            panel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_calculoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_altura)
                    .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel_calculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_peso)
                    .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel_resultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label_resultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label_resultado.setText("Resultado:");

        label_interpretacao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label_interpretacao.setText("Interpretação:");

        javax.swing.GroupLayout panel_resultadoLayout = new javax.swing.GroupLayout(panel_resultado);
        panel_resultado.setLayout(panel_resultadoLayout);
        panel_resultadoLayout.setHorizontalGroup(
            panel_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_interpretacao)
                    .addComponent(label_resultado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_resultadoLayout.setVerticalGroup(
            panel_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_resultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(label_interpretacao)
                .addGap(25, 25, 25))
        );

        label_edwardlacerda.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        label_edwardlacerda.setText("Designed by Edward Lacerda");

        javax.swing.GroupLayout panel_imcLayout = new javax.swing.GroupLayout(panel_imc);
        panel_imc.setLayout(panel_imcLayout);
        panel_imcLayout.setHorizontalGroup(
            panel_imcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imcLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel_imcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_titulo)
                    .addComponent(panel_calculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_imcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_edwardlacerda)
                .addContainerGap())
        );
        panel_imcLayout.setVerticalGroup(
            panel_imcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imcLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_calculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_edwardlacerda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_imc, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_imc, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        String userAltura = txt_altura.getText();
        String userPeso = txt_peso.getText();

        boolean validacao = userPeso.matches("[0-9]{1,3}[.][0-9]{0,5}|[0-9]{1,3}");
        boolean validacao2 = userAltura.matches("[0-9]{1,2}[.][0-9]{0,5}|[0-9]{1,2}");

        if (txt_altura.getText().isEmpty() || txt_peso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Os campos estão vazios!");
            txt_altura.setText(null);
            txt_peso.setText(null);

        } else if (validacao == false || validacao2 == false) {
            JOptionPane.showMessageDialog(null, "Valores inválidos\nUtilize formatação com pontuação\nExemplo: altura = 1.70!");
            txt_altura.setText(null);
            txt_peso.setText(null);
        } else {
            double altura = Double.parseDouble(txt_altura.getText());
            double peso = Double.parseDouble(txt_peso.getText());
            double imc = (peso / (altura * altura));
            DecimalFormat df = new DecimalFormat("#.00");
            label_resultado.setText("Resultado: " + df.format(imc));

            if (imc <= 18.5) {
                label_interpretacao.setText("Interpretação: Magreza");
            } else if (imc >= 18.5 && imc <= 24.9) {
                label_interpretacao.setText("Interpretação: Normal");
            }
            if (imc >= 25.0 && imc <= 29.9) {
                label_interpretacao.setText("Interpretação: Sobrepeso");
            } else if (imc >= 30.0 && imc <= 39.9) {
                label_interpretacao.setText("Interpretação: Obesidade");
            } else if (imc >= 40.0) {
                label_interpretacao.setText("Interpretação: Obesidade grave");
            }
        }


    }//GEN-LAST:event_btn_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JLabel label_altura;
    private javax.swing.JLabel label_edwardlacerda;
    private javax.swing.JLabel label_interpretacao;
    private javax.swing.JLabel label_peso;
    private javax.swing.JLabel label_resultado;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JPanel panel_calculo;
    private javax.swing.JPanel panel_imc;
    private javax.swing.JPanel panel_resultado;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_peso;
    // End of variables declaration//GEN-END:variables
}
